# Generated by Django 5.0.1 on 2024-11-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('document_image', models.ImageField(upload_to='documents/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
