# Generated by Django 5.0.1 on 2024-11-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_w2_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
