# Generated by Django 5.0.1 on 2024-11-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanapplication_monthly_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
